### ISSUE TITLE
Charge rate reports wrong values

### ISSUE THREAD

**Issue by DmitryNuzhdin** [eldruin/max170xx-rs#1]
When the battery discharges wrong values get reported (MAX17048). The reason for that is that this register is i16 formatted in reality and has negative values when the battery discharges. But the library converts them to u16. 

I know that it's an old repo, but I found this lib useful for me. Will you merge aa PR if I will make one with the fix :) ?

**Comment by eldruin** [comment]
Hi, thanks for finding it. I would certainly welcome a PR fixing that.
