### ISSUE TITLE
Multiple devices on I2C bus

### ISSUE THREAD

**Issue by tomhampshire** [eldruin/max170xx-rs#3]
Hi - is it possible to use this crate when there are more than one slave device on the I2C bus? I can see that the struct's init takes ownership of the I2C struct.

**Comment by eldruin** [comment]
Of course. You can have a look at the [shared-bus](https://crates.io/crates/shared-bus) crate for that.
It is also used in the [driver-examples](https://github.com/eldruin/driver-examples) repository.
